### PR TITLE
Tidy repo

### PR DESCRIPTION
**Pull request by DJSaunders1997**
PR to remove all unneeded files in the repo. The main branch was full of experimental code which realistically shouldnt have been in main in the first place. All of this experimental code has now been moved to the archive branch incase it is needed later.

This should hopefully tidy up everything and make any more PR's easier to review in the future.

Other improvements are:
1- Changing from reading the bearer token value from a non-commited python script to reading from environment variables.
2- Creating conda environment file for reproducibility
3- Using githubs reccomended .gitignore for python projects

### CODE REVIEW

**Comment by DJSaunders1997** [comment]
@97saundersj
How can I add you as a reviewer

**Comment by DJSaunders1997** [comment]
@97saundersj I've requested you join as a collaborator, I think I can add you once you've accepted.

**Comment by 97saundersj** [comment]
@DJSaunders1997 looks all good, want me to merge or want to do it yourself?

**Comment by DJSaunders1997** [comment]
@97saundersj 
image

**Pull request merged**
